### ISSUE TITLE
dashboard button press doesn't work as expected

### ISSUE THREAD

**Issue by Clumsy-Coder** [goolord/alpha-nvim#100]
I'm currently trying to figure out why selecting a button and pressing `Enter` key is not working

I get a `E21: Cannot make changes, 'modifiable' is off` instead

config
```lua
local alpha = require("alpha")
local dashboard = require("alpha.themes.dashboard")

dashboard.section.buttons.val = {
  dashboard.button("SPC f f" , "  Find file", ":Telescope find_files hidden=true no_ignore=true<CR>"),
}

alpha.setup(dashboard.config)
```

The weird thing is that if used 

```lua
dashboard.button("<leader>ff" , "  Find file", ":Telescope find_files hidden=true no_ignore=true<CR>")
```
instead, then pressing enter key works.

---
NOTE: I also have `<leader>ff` keymapped using
leader is `<space>`
```lua
vim.api.nvim_set_keymap("n", "<leader>ff", ":Telescope find_files hidden=true no_ignore=true<cr>", { noremap = true, silent = true } )
```

**Comment by Clumsy-Coder** [comment]
Found the cause of problem

https://github.com/goolord/alpha-nvim/blob/534a86b348b741ada5bb0d4b83c2c3da6763352a/lua/alpha/themes/dashboard.lua#L53

`sc` should be changed to `sc_`

`sc` will contain raw string. Ex: `SPC ff`
`sc_` is the formatted string. Ex: `<leader>ff`

It's the same for startify
https://github.com/goolord/alpha-nvim/blob/534a86b348b741ada5bb0d4b83c2c3da6763352a/lua/alpha/themes/startify.lua#L47

**Comment by goolord** [comment]
goood catch, i must have messed this up at some point when reverting some changes recently. thanks

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/commit/d54ce84559ee50500a1133d1c58daf9cd715525b

**Comment by dinhmai74** [comment]
I have the same issue now @goolord any way to fix it? It happens when I update to nvim nightly NVIM v0.8.0-dev-971-g3e0c262a6
<img width="678" alt="image" src="https://user-images.githubusercontent.com/40544043/187123664-47e82184-3c01-418d-8925-48f568c4eb53.png">

**Comment by goolord** [comment]
what does your config look like? works fine on my machine

**Comment by dinhmai74** [comment]
nvm @goolord , I  found the issue. I used this code 
`  button("h", "  Hapoon File  ", ":lua require('harpoon.ui').toggle_quick_menu()<cr>"),
`
which cause the bug -> change to `  button("h", "  Hapoon File  ", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>")` and it works fine
