### ISSUE TITLE
How to ignore files from a certain directory?

### ISSUE THREAD

**Issue by medwatt** [goolord/alpha-nvim#103]
I am using the startify theme and I would like to ignore all files from a given directory. For example, since I use firenvim, I don't start the MRU to have files from `/run/user/.*/firenvim'}`. With startify, I was able to do this with `
vim.g.startify_skiplist = {'/run/user/.*/firenvim'}`. How can I do that here?

**Comment by goolord** [comment]
atm you can redefine `startify.mru_opts.ignore`
https://github.com/goolord/alpha-nvim/blob/main/lua/alpha/themes/startify.lua#L109-L110
and then write your own predicate on the path & extension using lua

**Comment by medwatt** [comment]
Thanks for the reply. I am asking because I tried to write my own but couldn't get it to work. I hope you wouldn't mind helping out.

**Comment by goolord** [comment]
![image](https://user-images.githubusercontent.com/24906808/164932016-47ed9175-e16e-461c-b34f-aacd49633fdf.png)
sure, the function you want is `string.find`, it would probably end up looking like this
```lua
startify.mru_opts.ignore = function (path, ext)
  local ext_ignore = { "gitcommit" }
  return (string.find(path, '/run/user/.*/firenvim') ~= nil) or (string.find(path, "COMMIT_EDITMSG")) or (vim.tbl_contains(ext_ignore, ext))
```
