### ISSUE TITLE
Alpha sets window options, overriding lua config

### ISSUE THREAD

**Issue by bennypowers** [goolord/alpha-nvim#106]
Users with `init.lua` containing:
```lua
vim.o.number         = true
vim.o.relativenumber = true
```

will find that alpha overrides their config at https://github.com/goolord/alpha-nvim/blob/4781fcfea5ddc1a92d41b32dc325132ed6fce7a8/lua/alpha.lua#L424

Alpha should remember the user config and reset it when closing

**Comment by goolord** [comment]
it's set with `setlocal`, the configuration is entirely local to the alpha buffer. way more users want `nonu` out of the box for alpha than don't. what you are experiencing is probably a problem with lua's window option api that you're using in your branch. i linked the relevant issue in your PR https://github.com/neovim/neovim/issues/14670

**Comment by bennypowers** [comment]
yeah most likely. I've since updated my branch to solve that problem
