### ISSUE TITLE
`SPC ff`, `SPC fh`, `SPC fr`, `SPC fg`, and `SPC fm` are not woking for `dashboard-nvim theme`

### ISSUE THREAD

**Issue by tapyu** [goolord/alpha-nvim#108]
I've tried to follow the `quick start`'s section but I couldn't understand what commands `alpha-nvim` suppose I've mapped to `SPC ff`, `SPC fh`, `SPC fr`, `SPC fg`, and `SPC fm` when using `dashboard-nvim theme`. For the out-of-the-box config, none of these keymapping are working...

The `README.md` file says:
> this theme makes some assumptions about your default keybindings to customize the buttons, see :h alpha-example

It turns out that the [`alpha-example`](https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L167-L199) doesn't even set these keymaps. Rather, it sets only the button `q` and `e`. The unique keymap that works is `e` (new file).

# How to reproduce
1. save this code as `minimal_init.lua`
    ```lua
    require("packer").startup{function ()
      use 'wbthomason/packer.nvim'
      use {
        'goolord/alpha-nvim',
        config = function ()
            require'alpha'.setup(require'alpha.themes.dashboard'.config)
        end
      }
    end
    }
    ```
1. Run `nvim -u minimal_init.lua`
2. Test `SPC ff`, `SPC fh`, `SPC fr`, `SPC fg`, and `SPC fm`. They won't work

# Expected behavior
One of the following options:
- Having a `quick start`'s section with clearer instructions to make `SPC ff`, `SPC fh`, `SPC fr`, `SPC fg`, and `SPC fm` work.
- Making these keymaps already working without any extra configuration.
- Referencing a link where the user can understand how to configure it.

As it is written on `README.md`, it conveys the wrongly impression that these keys work, but they don't.

Thanks in advance.

**Comment by tapyu** [comment]
After struggling a lot to make out how to set this up. I suppose I've finally find out what are some of the commands that I should use:

```lua
local is_status_ok, alpha = pcall(require, "alpha")

if not is_status_ok then
  print("alpha plugin not found")
  return
end

local dashboard = require("alpha.themes.dashboard")

dashboard.section.buttons.val = {
  dashboard.button("SPC f f", "  Find file", ":Telescope find_files hidden=true no_ignore=true<CR>"),
  dashboard.button("SPC f h", "  Recently opened files", "<cmd>Telescope oldfiles<CR>"),
  dashboard.button("SPC f r", "  Frecency/MRU"),
  dashboard.button("SPC f g", "  Find word",  "<cmd>Telescope live_grep<cr>"),
  dashboard.button("SPC f m", "  Jump to bookmarks"),
  dashboard.button("SPC s l", "  Open last session", "<cmd>SessionManager load_last_session<CR>"),
}

alpha.setup(dashboard.config)
```

Anyone can say which command I should use got `SPC f m` and `SPC f r`? I really didn't understand a "quick start" which does not provides the basic functionalities :expressionless:

**Comment by EKYS12** [comment]
Just installed this plug in and experienced it myself as well. Out of the box the starting UI shows the hot keys like `space ff` but they do absolutely nothing. Either hotkeys the user are straight up shown on start up should work out of the box, or not be shown as the default hotkeys. If the point were to make users customize their shortcuts from the start, then the displayed shortcuts shouldn't exist and instead the program should encourage you to make new hotkeys.

**Comment by goolord** [comment]
yes the dashboard theme makes assumptions about what keybindings you already have by default, but so does the viml dashboard plugin. i don't have any interest in changing that

**Comment by goolord** [comment]
the dashboard theme without making assumptions about your existing keybindings would just be a header by default. this is pointless
