### ISSUE TITLE
Incompatibility with `telescope-ui-select.nvim`

### ISSUE THREAD

**Issue by tapyu** [goolord/alpha-nvim#109]
I've set up `alpha-nvim` to work along with `Shatur/neovim-session-manager` which, in turn, makes use of [telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim) to handle `vim.ui.select` with `telescope`. Whenever I try to select a session in a bare `neovim` command, `alpha-nvim` wrongly alert me that the current session have change.

# How to reproduce

1. save this file as `minimal_init.lua`
    ```lua
    require("packer").startup{function ()
      use 'wbthomason/packer.nvim'
      use 'nvim-lua/plenary.nvim'
      use 'nvim-telescope/telescope.nvim'
      use {'nvim-telescope/telescope-ui-select.nvim', requires =  'nvim-telescope/telescope.nvim'}
      use 'Shatur/neovim-session-manager'
      use {
        'goolord/alpha-nvim',
        config = function ()
            require'alpha'.setup(require'alpha.themes.dashboard'.config)
        end
      }
    end
    }


    -- section manager config
    local Path = require('plenary.path')
    require('session_manager').setup({
      sessions_dir = Path:new(vim.fn.stdpath('data'), 'sessions'), -- The directory where the session files will be saved.
      path_replacer = '__', -- The character to which the path separator will be replaced for session files.
      colon_replacer = '++', -- The character to which the colon symbol will be replaced for session files.
      autoload_mode = require('session_manager.config').AutoloadMode.Disabled, -- Define what to do when Neovim is started without arguments. Possible values: Disabled, CurrentDir, LastSession
      autosave_last_session = true, -- Automatically save last session on exit and on session switch.
      autosave_ignore_not_normal = true, -- Plugin will not save a session when no buffers are opened, or all of them aren't writable or listed.
      autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
        'gitcommit',
      },
      autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
      max_path_length = 80,  -- Shorten the display path if length exceeds this threshold. Use 0 if don't want to shorten the path at all.
    })

    require("telescope").setup {
      extensions = {
        ["ui-select"] = {
          require("telescope.themes").get_dropdown {}
        }
      }
    }

    -- load_extension
    require("telescope").load_extension("ui-select")
    ```
1. run `nvim -u minimal_init.lua`
2. `:SessionManager load_session` (you should have a session saved, of course. If you don't, just run `:SessionManager save_current session`)
3. Select any session.

You will see this behavior:
![Peek 2022-05-01 22-41](https://user-images.githubusercontent.com/22801918/166174807-02e7d594-6c34-42b1-9474-941b652a2194.gif)

# Expected behavior
`alpha-nvim` should go to session directly.

**Comment by goolord** [comment]
... I don't really know what's going on here but alpha doesn't touch sessions at all. i use neovim-session-manager  without telescope-ui-select.nvim and it works fine. I can try to dig around and see what's up with this though

**Comment by tapyu** [comment]
> but alpha doesn't touch sessions at all.

This statement might be true but that's not where the problem probably lies. It seems that `alpha-nvim` are seeing a modified unsaved buffer, when actually there isn't anything...

> i use neovim-session-manager without telescope-ui-select.nvim and it works fine

Yeah, this is right, I can reproduce the same here. It works fine without `telescope-ui-select.nvim`

> I can try to dig around and see what's up with this though

I can do it as soon as I have a free time, which is quite hard nowadays :cold_sweat:

**Comment by goolord** [comment]
yea you can't display text without creating a buffer. the buffer is `nofile` which i would suppose wouldn't effect the session, but idk

**Comment by GabMus** [comment]
A bit of a shot in the dark, but try calling the telescope-ui-select callback using vim.schedule

**Comment by benbrastmckie** [comment]
> ... I don't really know what's going on here but alpha doesn't touch sessions at all. i use neovim-session-manager without telescope-ui-select.nvim and it works fine. I can try to dig around and see what's up with this though

I'm trying to get this setup to work for me, i.e., alpha-nvim + neovim-sessions-manager. When I enter the command `SessionManager load_session` from the start screen it works great. However, I've also added the following button which does not work:
```
	dashboard.button("l", "Load session", ":SessionManager load_session <CR>"),
```
Instead, when I hit `l` for 'Load session' I get: "No such subcommand: load_sessions". I must be missing something small as it seems that it is close to working. Any help would be greatly appreciated.

**Comment by goolord** [comment]
the error message says "No such subcommand: load_session**s**"? or is that a typo only present in your comment

**Comment by benbrastmckie** [comment]
Yes my typo. It is in fact singular.

**Comment by goolord** [comment]
@benbrastmckie i finally figured out what your bug is. there is a space here `load_session <CR>` that's getting parsed as a session name by that plugin. just remove the space and your button should work 👍

**Comment by goolord** [comment]
@tapyu is this still a problem for you? i'm using these plugins in this way with no problems

**Comment by benbrastmckie** [comment]
Hey sorry for the slow reply. I got it working just great. Thanks for the help!
