### ISSUE TITLE
[Question] Close empty buffer after file open

### ISSUE THREAD

**Issue by chaesngmin** [goolord/alpha-nvim#11]
Hi, I have a question.

Any idea how to remove empty buffer after file is open from `dashboard or startify`?

**current**
![image](https://user-images.githubusercontent.com/15729866/132571333-ab948b7a-6454-438f-ab06-b15910b4c357.png)

**desired**
![image](https://user-images.githubusercontent.com/15729866/132571432-636406a8-8c2b-4520-a2cd-3e959050030d.png)

**Comment by goolord** [comment]
no, i've put some minimal effort into trying to fix this behavior but i haven't figured it out. i don't know how startify or dashboard do it. `BufUnload` for example fires before the new buffer has been unloaded, thus you can't delete the alpha buffer yet or there would be no buffers.

**Comment by hhn-pham** [comment]
This is a hacky workaround. Call a function which clears all empty buffers (found [here](https://newbedev.com/how-to-delete-all-empty-buffers-in-vim)).
```
function! CleanEmptyBuffers()
    let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && empty(bufname(v:val)) && bufwinnr(v:val)<0 && !getbufvar(v:val, "&mod")')
    if !empty(buffers)
        exe 'bw ' . join(buffers, ' ')
    endif
endfunction
```
then call it on non `alpha` filetypes:
```
autocmd WinEnter,BufRead,BufNewFile * if &ft != 'alpha' | set showtabline=2 | call CleanEmptyBuffers() | endif
```
Not sure if it's any good but it's working fine for me.

**Comment by goolord** [comment]
fixed in https://github.com/goolord/alpha-nvim/commit/667a820164aa33ca2195977dba07561fd8745d08
the empty buffer was *actually* the buffer vim opens by default on vimenter. no jank required

**Comment by goolord** [comment]
ok, maybe not *no* jank. i kinda forsee `vim.api.nvim_buf_delete(1, {})` maybe having some nasty interactions with other plugins. idk. probably won't be a problem unless any other plugins are messing with buffers on vimenter. i'll just let someone report if it's doing something nasty for them :)

**Comment by sadmanbd** [comment]
> ok, maybe not _no_ jank. i kinda forsee `vim.api.nvim_buf_delete(1, {})` maybe having some nasty interactions with other plugins. idk. probably won't be a problem unless any other plugins are messing with buffers on vimenter. i'll just let someone report if it's doing something nasty for them :)

This hides/disables the tabline for me after I open any file in the same buffer using `:e`. I have the following autocmd set up to disable tabline on the alpha buffer and re-enable it after opening a new file.

`autocmd FileType alpha set showtabline=0 | autocmd WinLeave <buffer> set showtabline=2`

Running `set showtabline=2` manually enables the tabline.

**Comment by goolord** [comment]
@sadmanbd change `WinLeave` to `BufUnload` and it should work

**Comment by jrafaaael** [comment]
> @sadmanbd change `WinLeave` to `BufUnload` and it should work

Hi! I try this but I still getting the empty buffer :(
