### ISSUE TITLE
When nvimTree opens the file, alpha is not closed

### ISSUE THREAD

**Issue by zlongCoding** [goolord/alpha-nvim#114]
When I opened the file via nvimTree, alpha was not closed
![7-0032](https://user-images.githubusercontent.com/20821148/173489569-1407bf00-089e-48fe-b321-ec2546d51a9b.jpg)

**Comment by konart** [comment]
Same here, but only for a certain filetypes. This happens when opening `lua` files but `golang` files do replace alpha.

**Comment by goolord** [comment]
this doesn't happen for me but i suspect *maybe* it's because i have
https://github.com/goolord/nvim/blob/main/lua/plugins/nvim-tree.lua#L46
`        update_focused_file = { enable = true },`

**Comment by goolord** [comment]
anyway, this is either an issue with nvimTree or with your specific configuration, i've done about all i can on alpha's side to integrate it with other plugins ¯\\\_(ツ)\_/¯

it's already 
```
vim.opt_local.bufhidden = 'wipe'
vim.opt_local.buflisted = false
vim.opt_local.buftype = 'nofile'
```

**Comment by dark-Jedi2108** [comment]
same happening for me too, any fix?

**Comment by goolord** [comment]
yeah so from what i gather the window picker for nvim-tree ignores `buftype = nofile` buffers, which will keep the alpha buffer open in a split, unless update_focused_file is set for some reason.

i can think of some workarounds for this but they're not really very pretty..

**Comment by hermitmaster** [comment]
I have a fairly basic nvim-tree config and I don't have this issue.
```lua
use {
    'kyazdani42/nvim-tree.lua',
    requires = 'kyazdani42/nvim-web-devicons',
    ft = 'alpha',
    config = function()
      local tree_cb = require('nvim-tree.config').nvim_tree_callback

      require('nvim-tree').setup {
        disable_netrw = true,
        ignore_buffer_on_setup = true,
        open_on_setup = true,
        view = {
          mappings = {
            custom_only = true,
            list = {
              { key = '<cr>', cb = tree_cb('edit') },
              { key = '<C-v>', cb = tree_cb('vsplit') },
              { key = '<C-x>', cb = tree_cb('split') },
              { key = 'h', cb = tree_cb('toggle_dotfiles') },
              { key = 'i', cb = tree_cb('toggle_git_ignored') },
              { key = 'R', cb = tree_cb('refresh') },
              { key = 'a', cb = tree_cb('create') },
              { key = 'd', cb = tree_cb('trash') },
              { key = 'q', cb = tree_cb('close') },
              { key = 'r', cb = tree_cb('rename') },
              { key = 's', cb = tree_cb('system_open') },
              { key = 'x', cb = tree_cb('cut') },
              { key = 'c', cb = tree_cb('copy') },
              { key = 'p', cb = tree_cb('paste') },
              { key = 'y', cb = tree_cb('copy_path') },
              { key = 'Y', cb = tree_cb('copy_absolute_path') },
              { key = 'K', cb = tree_cb('toggle_help') },
            },
          },
        },
      }
    end,
  }
```
I use `ft=alpha` to launch nvim-tree at startup after alpha.

**Comment by mosheavni** [comment]
Also experiencing this.
Any ideas?
