### ISSUE TITLE
The option `showtabline` is overwritten by Alpha

### ISSUE THREAD

**Issue by AxZxP** [goolord/alpha-nvim#116]
## Setup 
- Nvim 0.7
- Alpha commit ef27a59e5b4d7b1c2fe1950da3fe5b1c5f3b4c94

## How to reproduce
in my option I've set : `vim.opt.showtabline = 0`. If I open a file without transiting by Alpha dashboard I don't have any tabline. If I open the dashboard first and open a file I have this tabline.

<details>
  <summary>Screen</summary>

https://user-images.githubusercontent.com/68596777/174447460-44b2c910-e488-42b4-b953-05016ef3fe08.mp4

</details>

Is there a way for Alpha to honour this setting ?

**Comment by goolord** [comment]
alpha does not overwrite showtabline. what you're probably experiencing here is more than likely that the tabline will not show tabs for hidden or unlisted buffers, and if alpha is the only buffer open, then there are no unhidden or listed buffers to display in the tabline.

**Comment by goolord** [comment]
try adding
```lua
local oldsetup = vim.deepcopy(theme.opts.setup)
theme.opts.setup = function ()
  oldsetup()
  vim.cmd('setlocal buflisted')
end
```
to your config

**Comment by AxZxP** [comment]
Ok here is my alpha setup simplified for the sake of readability. I still have the same issue, but I really don't know if I translate well enough your instruction to my config ? In this situation, it doesn't change anything. 

```lua
local status_ok, alpha = pcall(require, "alpha")
if not status_ok then
  return
end

local dashboard = require "alpha.themes.dashboard"
local oldsetup = vim.deepcopy(dashboard.opts.setup)

dashboard.section.header.val = {
  "foo"
}

dashboard.section.buttons.val = {
  dashboard.button("f", " " .. " Find file", ":Telescope find_files <CR>"),
}

local function footer()
  return "bar"
end

dashboard.section.footer.val = footer()
dashboard.section.footer.opts.hl = "Type"
dashboard.section.header.opts.hl = "Include"
dashboard.section.buttons.opts.hl = "Keyword"
dashboard.opts.opts.noautocmd = true

dashboard.opts.setup = function ()
  oldsetup()
  vim.cmd('setlocal buflisted')
end

alpha.setup(dashboard.opts)
```

**Comment by AxZxP** [comment]
Issue unrelated with the plug-in but with an autocmd. Sorry and thank for the help.
