### ISSUE TITLE
Dashboard header is Italized

### ISSUE THREAD

**Issue by ankushKun** [goolord/alpha-nvim#117]
<details>
<summary>Here is my alpha config</summary>

```lua
local alpha = require("alpha")
local dashboard = require("alpha.themes.dashboard")

-- Set header
dashboard.section.header.val = {
[[     /\_____/\         ]],
[[    /  o   o  \  nyaa~ ]],
[[   ( ==  ^  == )       ]],
[[    )         (        ]],
[[   (           )       ]],
[[  ( (  )   (  ) )      ]],
[[ (__(__)___(__)__)     ]]
}

-- Set menu
dashboard.section.buttons.val = {
    dashboard.button( "f", " Find File", ":Telescope find_files<CR>"),
    dashboard.button( "l", " Find Word", ":Telescope live_grep<CR>"),
    dashboard.button( "r", " Recent"   , ":Telescope oldfiles<CR>"),
    dashboard.button( "s", " Config" , ":Config<CR>"),
    dashboard.button( "q", " Quit NVIM", ":qa<CR>"),
}

alpha.setup(dashboard.opts)

-- Disable folding on alpha buffer
vim.cmd([[autocmd FileType alpha setlocal nofoldenable]])
```
</details>

The ascii art for this cat in header is appearing _italicized_ and I am unable to figure out how to prevent it from doing that.

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/50258860/174479291-833bcd4e-0cc2-4124-9e34-dcb8305dbfc2.png)

</details>

how it looks
<i>
```
     /\_____/\         
    /  o   o  \  nyaa~ 
   ( ==  ^  == )       
    )         (        
   (           )       
  ( (  )   (  ) )      
 (__(__)___(__)__)     
```
</i>

how it should look
```
     /\_____/\         
    /  o   o  \  nyaa~ 
   ( ==  ^  == )       
    )         (        
   (           )       
  ( (  )   (  ) )      
 (__(__)___(__)__)     
```

I looked at other peoples configs and their ascii art seem to be non __italicized__ is there some value I can change in alpha config? Couldn't find anything related to this in example configs or `:help alpha`

**Comment by goolord** [comment]
the header uses the `Type` highlight group, which is italicized by your colorscheme. you can simply change
```lua
dashboard.header.opts.hl = "Special"
```
or whatever highlight group you want
