### ISSUE TITLE
Having no buttons in layout throws `Expected lua table` exception

### ISSUE THREAD

**Issue by drinkitup777** [goolord/alpha-nvim#119]
If the layout has no buttons in it, `alpha.nvim` will throw the following exception:
![screen](https://user-images.githubusercontent.com/59168253/176309946-778095e4-5a15-40d7-b1dd-bfd463221cc8.png).

**Steps to reproduce**
1. Make sure layout has no buttons in it. (It doesn't need to be completely empty. It just needs to have no buttons.)
    ```lua
    -- example layout
    require("alpha").setup {
        layout = {},
    }
    ```
2. Start `alpha.nvim`, either by starting a new instance of Neovim or calling `:Alpha`
3. Observe that an exception is thrown.

**Comment by goolord** [comment]
do you have a use case for a theme with no buttons??? willing to support it but i'm just curious. the only reason i left this unimplemented is because i wasn't sure where to place the cursor in the event there's nothing for the user to interact with, and maybe the check wastes cpu cycles most of the time

**Comment by drinkitup777** [comment]
My use case is a theme that actually does have buttons, but they're all buttons for recently-used files and recently-used sessions. On a fresh install of Neovim, there are no files or sessions in the history, so there are no buttons to show.

**Comment by goolord** [comment]
ok, buttonless layouts supported at 09e5374465810d71c33e9b097214adcdebeee49a

it's a relatively small change and there was no negative impact on startup time
