### ISSUE TITLE
Text highlighting doesn't begin at the first character

### ISSUE THREAD

**Issue by Zaedus** [goolord/alpha-nvim#120]
I found this really cool title I really like, but the only way it works is if I set the exact start and end character from the very left edge of the window like so:
```lua
{{"Title", 0, -1}, {"PmenuSel", 101, 111}}
```
![image](https://user-images.githubusercontent.com/42098470/177239548-d62b31ed-cdc1-4843-aca8-554a3f45b903.png)
The best idea I can come up with for me right now is to calculate it based on the number of columns in the current window, but that won't automatically adjust to a new window width. Is this a bug or is there a something I'm missing?

**Comment by goolord** [comment]
should be fixed in https://github.com/goolord/alpha-nvim/commit/84a1969725247613348f7f1a2ed84dc2ec61d35b

thanks for spotting this, i really have to reduce duplication so that stuff like this doesn't slip through :V

**Comment by Zaedus** [comment]
Wow! As I was messing with my config I was wondering "why did my cool title suddenly break?" Thanks for the fast fix!

**Comment by Zaedus** [comment]
Also, you miiiight've left a debug print in there.

**Comment by goolord** [comment]
oopsies

**Comment by goolord** [comment]
the joys of printf debugging 😞https://github.com/goolord/alpha-nvim/commit/411ce27d871f963256c0787bc4133cf945dd89d3

**Comment by Zaedus** [comment]
Yay! Its all up and running, and now it still works even if I resize the window! Thank you so much!
![image](https://user-images.githubusercontent.com/42098470/177258102-1aab590a-fd3e-45b0-b6de-262caba3b2bd.png)
