### ISSUE TITLE
Unable to override button higlight group

### ISSUE THREAD

**Issue by ChristianChiarulli** [goolord/alpha-nvim#128]
(https://github.com/goolord/alpha-nvim/blob/d54ce84559ee50500a1133d1c58daf9cd715525b/lua/alpha/themes/dashboard.lua#L44)

I am unable to change this highlight from "Keyword"

**Comment by goolord** [comment]
```lua
local function button(sc, txt, keybind, keybind_opts)
  local b = dashboard.button(sc,txt,keybind,keybind_opts)
  b.hl_shortcut = "foo"
  return b
end
```
should be sufficient
