### ISSUE TITLE
How to install and use in neovim without lua? 

### ISSUE THREAD

**Issue by seriiserii825** [goolord/alpha-nvim#129]
In my file with plugins i wrote
```
        Plug 'goolord/alpha-nvim'

        lua << EOF
          require'alpha'.setup(require'alpha.themes.dashboard'.config)
        EOF

```

Plugin was installed, but neovim was broken.

**Comment by goolord** [comment]
that seems right to me, what's broken about it?

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/issues/135#issuecomment-1207107021
it worked for this user, maybe what's wrong with your config is that the lua needs to be called after `call plug#end()`
