### ISSUE TITLE
Open Alpha on every new tab with autocmd

### ISSUE THREAD

**Issue by lockieluke** [goolord/alpha-nvim#134]
### Discussed in https://github.com/goolord/alpha-nvim/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **lockieluke** August  4, 2022</sup>
I tried making an auto command function to open alpha on each new tab I open but it didn't work, I am pretty sure that the function is actually triggered when a tab is opened but it just doesn't work

```lua
local alpha_start_group = vim.api.nvim_create_augroup("AlphaStart", { clear = true })
vim.api.nvim_create_autocmd("TabNew", {
  callback = function()
    alpha.start()
  end,
  group = alpha_start_group,
  buffer = 0
})
```
</div>

**Comment by goolord** [comment]
you want `"TabNewEntered"`, not `"TabNew"`. if you make that change this works for me @lockieluke

**Comment by lockieluke** [comment]
Thanks!
