### ISSUE TITLE
Alpha is breaking NvChad statusline

### ISSUE THREAD

**Issue by duraki** [goolord/alpha-nvim#138]
`alpha-nvim` is great, but it breaks [#NvChad/NvChad](https://github.com/NvChad/NvChad/) `statusline` when using CLI args. See below.

**Bug**

```
$ /usr/local/bin/nvim custom +Alpha
```

![Screenshot 2022-08-24 at 12 51 53](https://user-images.githubusercontent.com/5892610/186400698-d59a4eb2-1fd0-4c80-86d2-3760fadf6122.png)

**Correct** (excluding **Alpha**)

```
$ /usr/local/bin/nvim custom
```

![Screenshot 2022-08-24 at 12 53 02](https://user-images.githubusercontent.com/5892610/186400944-f23628e7-c957-4971-8a07-cd1f767e5ac5.png)

**Comment by goolord** [comment]
this is a feature built into NvChad https://github.com/NvChad/NvChad/blob/a67e19a439b1f8b214d2a471cbe8b0f98cb62ac1/lua/core/init.lua#L30

the danger with using neovim config distributions is that there's a bunch of configuration happening that you didn't write :)
