### ISSUE TITLE
dashboard shifts to left when you open and close nvim-tree

### ISSUE THREAD

**Issue by Rishabh672003** [goolord/alpha-nvim#139]
here's video of it happening - https://imgur.com/a/EjfCg7s

and here's my nvim-tree and alpha configs - [alpha-dashboard](https://raw.githubusercontent.com/Rishabh672003/Neovim/main/lua/user/startup-screens/startup-screen2.lua), [nvim-tree](https://raw.githubusercontent.com/Rishabh672003/Neovim/main/lua/user/nvim-tree.lua)

**Comment by goolord** [comment]
my best guess is that something in nvim-tree changes that made the interaction different, it's happened before. i'm gonna see if i can hook into wincmds with the autocmd api so that this doesn't happen again.

**Comment by goolord** [comment]
well, I can't apparentlly. I'm not sure any of the existing autocmd events will let me do that. it's just some quirk of nvim-tree, toggleterm works fine for me for example

adding this autocmd to your setup function should hotfix the behavior
```lua
            vim.api.nvim_create_autocmd({ 'CursorMoved' }, {
              group = vim.api.nvim_create_augroup("alpha_temp", {
                 clear = false
              }),
              pattern = '*',
              callback = function() alpha.redraw(conf, state) end,
            })
```

truthfully this will probably always behave jankily until https://github.com/neovim/neovim/issues/11532

**Comment by goolord** [comment]
i pushed a mildly more safe hotfix actually, this should be fixed now

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/commit/f17ded7c848c4200e2bb876095965688211f1502

**Comment by Rishabh672003** [comment]
@goolord yeah that seems to fix it, thank you
