### ISSUE TITLE
Create bookmarks to files and keep the icons.

### ISSUE THREAD

**Issue by rafamadriz** [goolord/alpha-nvim#14]
Right now I have something like this to have bookmarks to files:

```lua
    startify.section.bottom_buttons.val = {
        startify.button(
            "c",
            "~/.config/nvim/lua/config.lua",
            ":e ~/.config/nvim/lua/config.lua<CR>"
        ),
        startify.button("i", "~/.config/nvim/init.lua", ":e ~/.config/nvim/init.lua<CR>"),
        startify.button(
            "P",
            "~/.config/nvim/lua/modules/plugins/init.lua",
            ":e ~/.config/nvim/lua/modules/plugins/init.lua<CR>"
        ),
```

But, as you can see, it doesn't show up with icons.

![Screenshot_20210909_212356](https://user-images.githubusercontent.com/67771985/132779268-1bd30e23-215b-4a10-a932-d1d5dcc9516c.png)

This is just a nitpick and I'm happy with it not showing icons for those files, but I was wondering if it was possible to make it so I can create bookmarks to files and have it with icons. 

Also, not related to this issue but how can I change and add titles ? I've looking through the docs and playing around with a few options but can't figure it out. 

For example, I'd like to add "Bookmarks" above those files. and I'd like to change the MRU from this image:
![Screenshot_20210909_213101](https://user-images.githubusercontent.com/67771985/132779724-8abec2bb-e775-45f8-8f7e-92dccb78cab8.png)

To something else.

**Comment by goolord** [comment]
ok, `icon` and `file_button` are exported. you should be able to write your bookmarks like 
```lua
startify.file_button( "c", "~/.config/nvim/lua/config.lua" ),
```
and get the icon + highlighting

**Comment by goolord** [comment]
> Also, not related to this issue but how can I change and add titles ? I've looking through the docs and playing around with a few options but can't figure it out.
>
> For example, I'd like to add "Bookmarks" above those files. and I'd like to change the MRU from this image:

this level of granularity in configuration is frankly annoying to support.. after a certain point it becomes easier to just define your own `opts`. the startify module should export everything you would need to make your own layout using startify widgets.

**Comment by goolord** [comment]
this isn't a "hard no", I just don't know where I need to draw the line in the sand when it comes to these themes that are meant to mimic the look and feel of other greeter plugins

**Comment by rafamadriz** [comment]
> ok, `icon` and `file_button` are now exported [fb47b78](https://github.com/goolord/alpha-nvim/commit/fb47b78d89e31c15344f66550f13c42a729f4100). you should be able to write your bookmarks like
> 
> ```lua
> startify.file_button( "c", "~/.config/nvim/lua/config.lua" ),
> ```
> 
> and get the icon + highlighting

The order is inverted, it needs to be:

```lua
startify.file_button("~/.config/nvim/lua/config.lua" , "c"),
```

Otherwise it gives an error. 

> this level of granularity in configuration is frankly annoying to support.. after a certain point it becomes easier to just define your own opts. the startify module should export everything you would need to make your own layout using startify widgets.

That's a fair point.

**Comment by goolord** [comment]
my mistake. i'll think on this, there might be a solution that doesn't suck too bad

**Comment by goolord** [comment]
somehow i missed that with sections you can already pretty easily rearrange the layout with minimal effort.

example moving the header to the bottom: 
```lua
    startify.opts.layout = {
        {type = "padding", val = 2},
        startify.section.top_buttons,
        startify.section.mru,
        startify.section.mru_cwd,
        {type = "padding", val = 1},
        startify.section.bottom_buttons,
        {type = "padding", val = 1},
        startify.section.header,
        startify.section.footer,
    }
```

:)

**Comment by evantancy** [comment]
hi is it possible to still add this to our own configs? like if i have the line `local startify = require("alpha.themes.startify")` just use `startify.opts.layout = {...}` to reorder the layout?

**Comment by goolord** [comment]
yes
