### ISSUE TITLE
AlphaRedraw: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Strongleong** [goolord/alpha-nvim#140]
When I type command `:AlphaRedraw` I get these errors:

![image](https://user-images.githubusercontent.com/17177071/187013446-320badcb-641c-4653-a71b-bdb8bf0fdd3d.png)

It redraws successfully tho

**Comment by goolord** [comment]
fixed @ https://github.com/goolord/alpha-nvim/commit/ea7241855a55f33710833afb22fc91489e162c4f

**Comment by Strongleong** [comment]
Thx. Everything works now.
