### ISSUE TITLE
alpha opens telescope.nvim prompt in normal mode

### ISSUE THREAD

**Issue by gmr458** [goolord/alpha-nvim#141]
this only happens to me recently, it didn't happen before, when I open telescope.nvim the prompt is in normal mode by default.

my config:
```lua
local alpha_loaded, alpha = pcall(require, "alpha")

if not alpha_loaded then
    print("alpha not loaded")
    return
end

local dashboard = require("alpha.themes.dashboard")

dashboard.section.header.val = require("config.headers").Fraktur

local opts = { noremap = true, silent = true }

dashboard.section.buttons.val = {
    dashboard.button("tff", "  Find file", ":Telescope find_files hidden=true no_ignore=true<CR>", opts),
    dashboard.button("tfg", "  Live grep", ":Telescope live_grep preview=true<CR>", opts),
    dashboard.button("tfr", "  Recent File", ":Telescope oldfiles preview=false<CR>", opts),
    dashboard.button("q", "  Quit NVIM", ":qa<CR>", opts),
}

alpha.setup(dashboard.config)
```

when I run the telescope.nvim commands that are in my configuration manually, the prompt is automatically in insert mode

**Comment by benjaminroest** [comment]
Same problem for me.

**Comment by jpoppe** [comment]
It broke with this commit: https://github.com/goolord/alpha-nvim/commit/6af3b19d94e1660e558d6b7382e198a31945f9b9

**Comment by goolord** [comment]
fixed in https://github.com/goolord/alpha-nvim/commit/d2336550abec27c6af8be4ed5045fb4fa82a9c93

feedkeys being mysterious to me, again 😓
