### ISSUE TITLE
No alpha splash screen if some command is ran with `+` when starting nvim

### ISSUE THREAD

**Issue by WhiteBlackGoose** [goolord/alpha-nvim#142]
Hi, thanks for this plugin.

Here's the bug. If you start nvim as usual, it works as expected. But if you do, say,
```
nvim '+lua print("hello")'
```
The default nvim's splash screen appears

**Comment by WhiteBlackGoose** [comment]
Invoking `:Alpha` though shows the splash screen

**Comment by goolord** [comment]
this is an intentional feature of alpha

**Comment by goolord** [comment]
people use the + command syntax for scripting, and I presume most people don't want to start up a buffer they're not going to see or interact with. i tried to make this plugin as annoyance free as possible by default. if you still want to see `Alpha` then just invoke nvim like this`nvim +Alpha +"echo 'foo'"`

**Comment by WhiteBlackGoose** [comment]
Oh, lol, fair enough. Thanks
