### ISSUE TITLE
MRU numbers starting at 10

### ISSUE THREAD

**Issue by medwatt** [goolord/alpha-nvim#147]
I noticed a couple of days ago that all recently used files begin at 10 instead of 0. I haven't changed my config for alpha since the day I installed it. I even deleted the "shada" folder to delete the history, but the numbers still start at 10. Any ideas why?

**Comment by sbulav** [comment]
Having the same issue, it was introduced by this commit: https://github.com/goolord/alpha-nvim/commit/aabb41bd1235dc8e0a4af88c42d42baa6c6a56b0

As I see it, now 0-10 reserved for MRU CWD, 1-20 MRU
