### ISSUE TITLE
Change color for specific characters in header

### ISSUE THREAD

**Issue by xbladesub** [goolord/alpha-nvim#151]
Is there any way to interpolate/change color for specific characters in header?

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L169

**Comment by GabMus** [comment]
This doesn't work for header, setting dashboard.header.opts.hl to something like `{{'DiagnosticError', 0, -1}, {'Incluide', 0, -1}}` makes the header text use the default foreground color.

**Comment by goolord** [comment]
yes, it does work for the header, the header is just `type = "text"`, the problem with that snippet is that the range for both of those highlight groups is the same
