### ISSUE TITLE
Setting button keybinding to "h" persists

### ISSUE THREAD

**Issue by jtye-dsldhomes** [goolord/alpha-nvim#153]
My dashboard.section.buttons.val:

dashboard.section.buttons.val = {
	dashboard.button("s", "  Sync plugins", updates),
	dashboard.button("m", "  Mason", [[<cmd>Mason<cr>]]),
	dashboard.button("f", "  Find files", [[<cmd>Telescope find_files<cr>]]),
	dashboard.button("r", "  Restore session", [[<cmd>silent! RestoreSession<cr>]]),
	dashboard.button("h", "  Harpoon", [[<cmd>lua require("harpoon.ui").toggle_quick_menu()<cr>]]),
	dashboard.button("w", "  Workspaces", [[<cmd>Telescope workspaces<cr>]]),
	dashboard.button("t", "  Telescope", [[<cmd>Telescope<cr>]]),
	dashboard.button("z", "  Full screen", [[<cmd>lua require("config.functions").ToggleZenMode()<cr>]]),
	dashboard.button("e", "  Empty buffer", [[<cmd>enew<cr>]]),
	dashboard.button("q", "  Quit NVIM", [[<cmd>qa<cr>]]),
}

It's not a problem with harpoon per se, because if I set any of the buttons to "h", when I load a buffer, pressing h will execute whatever I have configured for that button.

If I change buttons to:

	dashboard.button("h", "asdf", [[<cmd>echo 'asdf'<cr>]]),

Pressing h in a buffer will echo 'asdf':

![image](https://user-images.githubusercontent.com/62751493/197528957-6361e5b6-7248-4e08-adee-dc9f80531565.png)

**Comment by goolord** [comment]
the keybindings are buffer local, so that's odd

**Comment by jtye-dsldhomes** [comment]
This seems to be an issue with the combination of fold-preview.nvim being lazy loaded with packer on "CursorHold".  I think keymap-amend.nvim is amending binding whatever alpha sets to h to persist after alpha closes.

**Comment by axieax** [comment]
I've run into the same issue with leap.nvim `s` bindings (although not set for some reason). Disabling keymap-amend did not seem to resolve the problem, which is quite odd.
