### ISSUE TITLE
What are sections?

### ISSUE THREAD

**Issue by Gremious** [goolord/alpha-nvim#162]
I've read the documentation but it doesn't mention much about what sections are and how to use them.

It's all a bit confusing, since the layout map can take a mix of "sections" and arbitrary user elements together e.g.

```lua
config.layout = {
	section.header,
	{ type = 'padding', val = 2 },
	section.buttons,
	...
}
````

but then the sections are pretty much fully configurable anyway?

Also the doc mention a `buttons` as well as a `top_buttons` section (which also implies a bottom_buttons), though top_buttons isn't real anymore I think since I get a lua error on trying to use that. With that said:

1. What are the sections, e.g. when do I prefer to use `section.buttons` as opposed to just putting buttons in the layout?
2. Are they just groups e.g. `{ type = 'group', val = { ... } }` or are they treated in any special way by alpha? Asking because they seem to be in a separate field, outside of `layout`.
3. Is there just a list of all possible sections and what they're supposed to represent?
4. Can I make my own sections, and if so, how?
5. Please consider adding this information into the documentation.

Thanks 👍

**Comment by goolord** [comment]
yeah, you have the right idea. I just wanted to provide a simpler api for doing small mutations to alpha themes, like changing the header text or something.

**Comment by goolord** [comment]
it's kinda a quirk of lua i suppose, the `layout` array is really a table with number indexes, if you give them a string as the key it can sort the table in funny ways

**Comment by Gremious** [comment]
Yeah that's reasonable, and honestly appreciated - now that I know what it does it does it makes sense.
