### ISSUE TITLE
Prevent the automatic creation of new sessions

### ISSUE THREAD

**Issue by benbrastmckie** [goolord/alpha-nvim#184]
This is a great plugin and works perfectly for me. However, I notice that `alpha-nvim` automatically creates new sessions when I open different files (one's I may not return to like when I use `fire-nvim` to write text in my browser with NeoVim). 

What I would like is to be able to create a new session when I have a new project, delete sessions when those projects are finished, and for Alpha to not create any other sessions by itself. Is this currently an option? I didn't see anything in the Readme on this topic, nor did I find other issues relating to this matter. Thanks again for a great plugin!

**Comment by goolord** [comment]
what plugin are you using for session management?

**Comment by goolord** [comment]
or by "session" do you mean buffer?

**Comment by benbrastmckie** [comment]
Right... I'm using `Shatur/neovim-session-manager`. Looking into the config there I figured it out. Thanks for the redirection.
