### ISSUE TITLE
Error executing alpha.lua line 372

### ISSUE THREAD

**Issue by Mte90** [goolord/alpha-nvim#19]
![Screenshot_20210910_174228](https://user-images.githubusercontent.com/403283/132880840-71fbb1c6-d595-482c-9760-9df9c5610856.png)

I am getting this error when I press as example `1` or `g`.
I am getting this on terminal but also inside neovim-qt.

**Comment by goolord** [comment]
how am i meant to reproduce this? i understand your desire for privacy but you have censored the buttons you are saying cause this error. what commands are those buttons mapped to?

**Comment by goolord** [comment]
i'm guessing this is related to the autocmd cleaning up the redraw function not being fired. should maybe be cleaned up in https://github.com/goolord/alpha-nvim/commit/0086e21b24d9276b15fd53a0cd10ec0f62d55a94

**Comment by Mte90** [comment]
Sorry that I forgot to mention some info of the files.
I am getting this error with any kind of file that I have locally like php or js.
To get the error i just need to move the cursor to one of the button and press enter or use the shortcut of the button.

I saw the commit I will check on monday :-)

**Comment by Mte90** [comment]
I can confirm that the latest updates fix the issue :-)
