### ISSUE TITLE
Feature request: Manipulate MRU

### ISSUE THREAD

**Issue by comiluv** [goolord/alpha-nvim#192]
* Description
I want a command that can remove certain elements in MRU list or completely reset MRU list
* Why?
I might be wrong but sometimes after editing files stored in HDD or external HDD, when these storage devices go to sleep and I run Neovim again it takes a long time to start up Neovim just because some files in MRU list are stored in devices that are asleep
* How?
1) Moving cursor on the number inside brackets and pressing a hotkey such as "x" to remove the selected entry from the list
2) Commands such as ```:Alpha rm **number**``` to remove the numbered entry
3) Commands such as ```:Alpha reset``` to completely reset MRU list

**Comment by goolord** [comment]
> Neovim just because some files in MRU list are stored in devices that are asleep

i think you are misunderstanding how the list works/is populated. the list is fetched from the oldfiles in the shada file https://neovim.io/doc/user/starting.html#shada-file, which neovim usually reads weather or not this plugin is even installed.

> Moving cursor on the number inside brackets and pressing a hotkey such as "x" to remove the selected entry from the list
    Commands such as :Alpha rm **number** to remove the numbered entry
    Commands such as :Alpha reset to completely reset MRU list

this is a really bizarre request and I don't think I want to accommodate it. fwiw you can define this yourself very easily simply by defining a command which mutates this table and calls `AlphaRedraw`

https://github.com/goolord/alpha-nvim/blob/3847d6baf74da61e57a13e071d8ca185f104dc96/doc/alpha.txt#L217-L227
