### ISSUE TITLE
Terminal Header overlapping recent files

### ISSUE THREAD

**Issue by dwijesinghe** [goolord/alpha-nvim#193]
Hi, 

Love this plugin :) I've been working on customizing my alpha config to show an ASCII version of the Neovim logo using `ascii-image-converter` and my recent files. However I think I might be misunderstanding how to configure the alpha layout properly. Here's the alpha portion of my `config.lua`:

```
local alpha = require("alpha")
local alpha_theme = require("alpha.themes.theta")
require("alpha.term")

local alpha_header = {
	type = "terminal",
	command = "cat | ascii-image-converter --color " .. os.getenv("HOME") .. "/Code/neovim_logo_cropped.png -W 40",
	width = 40,
	height = 50,
	opts = {
		position = "center",
		redraw = true,
		window_config = {},
	},
}

alpha_config = alpha_theme.config
alpha_config.layout[2] = alpha_header
alpha_config.layout[3] = { type = "padding", val = 2 }
alpha_config.layout[6] = { type = "padding", val = 2 }

alpha.setup(alpha_config)
```

However this results in the following display, where the terminal output is overlapping the Recent Files section. Am I misconfiguring the layout? I thought the layout table was rendered in order from top to bottom but it looks like that isn't the case here:

![Screenshot 2023-03-21 at 9 30 46 AM](https://user-images.githubusercontent.com/3373777/226681003-74f8b8bc-28dc-493b-adc7-59f1906892f6.png)

**Comment by goolord** [comment]
hmm it should be, lua tables are kinda weird so it could be looping through the layout table in a weird way. i'm not sure. i'll look into this when i get some time

**Comment by dwijesinghe** [comment]
@goolord I just updated, but it looks like that just moved everything further down for me (see screenshot). Am I doing something wrong here? It looks as if the terminal floating window is getting padded instead of the subsequent content. If it helps I'm using iTerm2.
![Screenshot 2023-03-21 at 11 54 10 AM](https://user-images.githubusercontent.com/3373777/226712450-42d22420-ed3f-47e7-8f65-40be4f157f31.png)

**Comment by goolord** [comment]
you have to set the height of your window to the correct height. eyeballing it, it looks like your ascii image is 24 lines tall, so set `height = 24`

**Comment by dwijesinghe** [comment]
@goolord 🤦‍♂️ got it. Thank you so much for the fast response and quick fix!
