### ISSUE TITLE
How to set cursorline

### ISSUE THREAD

**Issue by BLACKSWORD0** [goolord/alpha-nvim#197]
It's a really beautiful plugin.   But when i try to set cursorline like this
<img width="1722" alt="CleanShot 2023-03-23 at 15 02 46@2x" src="https://user-images.githubusercontent.com/56479341/227127930-8467d3fa-2f84-4965-b715-0344ebb3f785.png">
I have  to input  this command after start neovim
```
:set cursorline. 
```
 I try to add this command in my config file  init.vim   but it doesn't work.  

I still try to add the following in my config file
```
autocmd FileType alpha set cursorline
```
But this doesn't work either.  I think I must be missing something.       Could you tell me  how to  set cursorline in alpha ?

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/blob/dafa11a6218c2296df044e00f88d9187222ba6b0/doc/alpha.txt#L339

`autocmd User AlphaReady setlocal cursorline` should work fine
