### ISSUE TITLE
Where do I find/put the config files?

### ISSUE THREAD

**Issue by DonjiKong** [goolord/alpha-nvim#198]
please *read the documentation* before asking questions about configuration or creating a feature request

for bugs: provide the expected behavior and the actual behavior, and screenshots if you want to be nice

**Comment by goolord** [comment]
read a beginners guide, or a package manager's documentation
https://github.com/folke/lazy.nvim

**Comment by DonjiKong** [comment]
I did, I don't even know what to look for, could you give me a smidgen of direction? I would really appreciate it!

**Comment by DonjiKong** [comment]
Im using packer
