### ISSUE TITLE
Padding broken when using wilder.nvim

### ISSUE THREAD

**Issue by koopa1338** [goolord/alpha-nvim#210]
Hi,

it seems that the commit 5b7ef660c6f80fbd04cccdf69624bf8c47513471 broke padding when using wilder.nvim (see screenshots). Other floating windows, e.g. from lazy or mason are not breaking the padding of alpha.

![alpha_ok](https://github.com/goolord/alpha-nvim/assets/20669804/3304abb5-cdbb-4950-9269-6456f4088d47)

![alpha_broken](https://github.com/goolord/alpha-nvim/assets/20669804/fed42df5-c334-4512-ba42-8ec5139458ea)

Edit: also leaving the cmdline triggers an "Column value outside range" error [here](https://github.com/goolord/alpha-nvim/blob/main/lua/alpha.lua#L632)

**Comment by goolord** [comment]
ok i started using the WinResized event and it seems to have fixed it. @koopa1338 confirm?

**Comment by koopa1338** [comment]
Thanks for the quick response, I tested the latest commit, and that fixed it for me :+1: 
Just for someone that has a similar issue and is using wilder.nvim, there is a tracking [issue](https://github.com/gelguy/wilder.nvim/issues/164) for a bug that shows the same behavior for other plugins.

**Comment by goolord** [comment]
i think there is technically still a pathological case where you resize the window and open the wildmenu on the same frame, but uhhh just don't do that 😅
