### ISSUE TITLE
Commit 1dcd325e2 broke lazynvim

### ISSUE THREAD

**Issue by joshuanave** [goolord/alpha-nvim#211]
please *read the documentation* before asking questions about configuration or creating a feature request

for bugs: provide the expected behavior and the actual behavior, and screenshots if you want to be nice

Testing out lazyvim and been tinkering a bit. Today I had an update for alpha-vim and i installed it. This is a fresh lazynvim install. After installing, I get a few different errors, screen shot below. 
![Screenshot 2023-05-09 at 2 45 00 PM](https://github.com/goolord/alpha-nvim/assets/18632315/51575f9a-16c0-4cb0-83c2-291d89840602)

This is again with a fresh install of lazynvim using the method described [here](https://www.lazyvim.org/installation)
i changed the lock file to point to the following commit ```eaeb20d25b36880678141534479a0d99591be9a1```  and the error doesn't happen.

**Comment by MoaidHathot** [comment]
I don't think this is related to LazyVim. This also reproduce for me, and I do not use LazyVim.

**Comment by goolord** [comment]
fixed here https://github.com/goolord/alpha-nvim/commit/1838ae926e8d49fe5330d1498ee8289ae2c340bc

my advice to you: i personally only test on HEAD neovim, if you're using a version of neovim without the `WinResized` patch you are subjecting yourself to a worse, more buggy experience.

**Comment by goolord** [comment]
also, that branch will probably be removed as soon as the latest neovim release supports the `WinResized` event

**Comment by MoaidHathot** [comment]
Thanks @goolord !
