### ISSUE TITLE
line numbers are not hidden when using statuscolumn

### ISSUE THREAD

**Issue by cliarena** [goolord/alpha-nvim#214]
Alpha-nvim shows line numbers when setting:
`statuscolumn = "%s%{v:relnum?v:relnum:v:lnum}%C"`
i expect line numbers to be hidden

![Screenshot from 2023-05-14 09-25-02](https://github.com/goolord/alpha-nvim/assets/74734861/4807eafe-628a-4ac1-9782-56befae92e27)

**Comment by rphuber** [comment]
The issue is that your settings for status column overwrite that functionality.  It always sets the line numbers.  You need to first do a check to see if numbers should be shown.  Something like:
`%s%{&nu?(&rnu && v:relnum?v:relnum:v:lnum):''}%C`
