### ISSUE TITLE
[Question] Dont understant hl prop

### ISSUE THREAD

**Issue by AethesticCoder** [goolord/alpha-nvim#215]
How do you change the font from italic, bold, normal and how do you put custom colors or default colors the value hl recieve a string but waht tipy of string should i pass for colors ?

**Comment by goolord** [comment]
the string is a highlight group. https://neovim.io/doc/user/syntax.html#:highlight

**Comment by AethesticCoder** [comment]
ok i understand this are the types

![image](https://github.com/goolord/alpha-nvim/assets/70770072/50914d30-8194-4e1a-8fc4-6a32cd7d3ea4)

and some colors are aplied depending of the value but i stil dont kwon what are the numbers and how to put it in bold i try some styles but nothing in bold

**Comment by AethesticCoder** [comment]
i try to put the numbers of this table but still dont show any color 

![image](https://github.com/goolord/alpha-nvim/assets/70770072/c69a2a92-1f69-4fd2-a942-d30ffd5b811c)

**Comment by goolord** [comment]
no, the numbers in the alpha api are the range to highlight. create a highlight group like how the docs i sent you show you and then set "hl" to that group. if you need to learn more about how to create a highlight group and you can't read the documentation, google it, respectfully

**Comment by AethesticCoder** [comment]
now i understand thanks, and sorry if it was a stupid question i am new to neovim, kwon the number are the ranges help a lot thanks for the help

**Comment by goolord** [comment]
no problem, sorry for not being more helpful, good luck 👍
