### ISSUE TITLE
Empty button is allowed, but it throws error

### ISSUE THREAD

**Issue by Zeioth** [goolord/alpha-nvim#217]
I'm trying to create an emply button row like this

```lua
 dashboard.section.buttons.val = {
     dashboard.button( "n", "📄  New     " , ':ene <BAR> startinsert <CR>'),
     dashboard.button( "e", "🪿  Recent  " , ':Telescope oldfiles<CR>'),
     dashboard.button( "r", "🐍  Ranger  " , ':Ranger<CR>'),
     dashboard.button( "s", "🔎  Sessions" , 'SessionManager! load_session<CR>'),
     dashboard.button( "p", "💼  Projects" , ':Telescope projects<CR>'),
     dashboard.button( "  ", " " , ' '), -- < ----This one
     dashboard.button( "q", "quit"         , ':exit<CR>'),
     --  --button("LDR f '", "  Bookmarks  "),
 }

```

You can see the result is the expected. It leaves an emply line with no action.
![screenshot_2023-05-22_00-32-22_245613975](https://github.com/goolord/alpha-nvim/assets/3357792/b260ecd5-caff-40de-b4c7-b4135eaddbb6)

The problem is this provokes an error in alpha.
![screenshot_2023-05-22_00-34-37_957827745](https://github.com/goolord/alpha-nvim/assets/3357792/0dd15e6d-2cc5-4efc-8a70-3efd37533368)

**Comment by goolord** [comment]
yeah i have pretty much no interest in fixing this. it's an interpreted & dynamically typed language, adding robust error checking would not only pollute the code but also come at a runtime cost. doing something stupid and seeing an error message is good enough

**Comment by goolord** [comment]
you don't need a button, you can just use a padding element or something

**Comment by Zeioth** [comment]
It worked fine         

``` lua
      dashboard.section.buttons.val = {
        dashboard.button("n", "📄 New     ", ':ene<CR>'),
        dashboard.button("e", "🌺 Recent  ", ':Telescope oldfiles<CR>'),
        dashboard.button("r", "🐍 Ranger  ", ':Ranger<CR>'),
        dashboard.button("s", "🔎 Sessions", 'SessionManager! load_session<CR>'),
        dashboard.button("p", "💼 Projects", ':Telescope projects<CR>'),
        dashboard.button("", ""),   -- <---- 2 arguments instead of 3
        dashboard.button("q", "   Quit", ':exit<CR>'),
      }

```
