### ISSUE TITLE
Alpha (maybe) blocking -c commands?

### ISSUE THREAD

**Issue by mara-kr** [goolord/alpha-nvim#22]
Hi! I have a shell alias `journal` that maps to `nvim -c "WikiJournal"` (using [wiki.vim](https://github.com/lervag/wiki.vim)). The issue: running `journal` from shell takes me to my alpha start screen instead of to my journal in wiki.vim. From the alpha start screen, I can run`:WikiJournal` without any issues, but passing in commands from shell doesn't seem to cooperate.
I'm synced with main, nvim v0.5.0.

Love the plugin! Happy to help fix, I just don't know where to start.

**Comment by goolord** [comment]
fixed in https://github.com/goolord/alpha-nvim/commit/f3232015014e1e276dcf1a091fd059b641f17a22

i'm not really happy with how janky it is to specify the conditions under which `alpha` shouldn't launch at `VimEnter`, but i guess it's better to be restrictive

**Comment by goolord** [comment]
unintended side effect: this will trick https://github.com/dstein64/vim-startuptime into reporting a faster startup time than reality since it passes `-c ':q'` to nvim
