### ISSUE TITLE
Unknown function: virtcol2col for older version

### ISSUE THREAD

**Issue by irfanbacker** [goolord/alpha-nvim#226]
Error when starting with alpha:
```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: Vim:E117: Unknown function: virtcol2col
stack traceback:
        [C]: in function 'virtcol2col'
        ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:637: in function 'move_cursor'
        ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:526: in function <...are/nvim/site/pack/packer/start/alpha-nvim/lua/alph
a.lua:525>
```

nvim version: 0.7.2
Looks like [this commit](https://github.com/goolord/alpha-nvim/commit/eaeb20d25b36880678141534479a0d99591be9a1) is breaking it for older versions. Is this version not supported anymore?

**Comment by goolord** [comment]
that's correct. i'm only going to support the latest release version of neovim. if you need a version of this plugin that supports your version of neovim i would suggest pinning to a working commit
