### ISSUE TITLE
Not an Editor command

### ISSUE THREAD

**Issue by brycepg** [goolord/alpha-nvim#227]
require'alpha'.setup(require'alpha.themes.startify'.config)

E5113: Error while calling lua chunk: C:\Users\Z\AppData\Local\nvim\init.lua:175: C:\Users\Z\AppData\Local\nvim\init.lua..C:\Users\Z\AppData\Local\nvim/vimrc.vim, line 11: Vim:E492: Not an editor command: require'alpha'.setup(require'alpha.themes.startify'.config)

**Comment by goolord** [comment]
`require` is a lua function, read a beginners guide to configuring neovim, this issue tracker is not a help forum

**Comment by brycepg** [comment]
I got some time to take a look at it and make it work. Thank you for making such a nice plugin.

The README configuration for lazy.nvim has an issue with installation because `opts` is evaluated before the plugin is installed causing an error which stops installation in its tracks, might require a assigned to `init=` or to simply make the setup call after lazy.nvim is instantiated.
