### ISSUE TITLE
[BUG] Attempt to get length of local "fn_start"

### ISSUE THREAD

**Issue by vuki656** [goolord/alpha-nvim#23]
Hey, I updated the plugin today and it seems something broke.

I didn't change anything since installing it so it's likely something internal. 

On nvim startup, I get this error

![Screenshot from 2021-09-13 20-09-10](https://user-images.githubusercontent.com/8104698/133134793-e75442e7-ccfd-41b6-a551-217e3ad00534.png)

Usage: 
`require("alpha").setup(require("alpha.themes.startify").opts)`

Let me know if i can provide any other info to help with debugging.

**Comment by guilhermeprokisch** [comment]
Same here

**Comment by goolord** [comment]
fixed. sorry, i tested the change that broke this but didn't hit the bad edge case
