### ISSUE TITLE
fails to open files with $ in the name

### ISSUE THREAD

**Issue by DanielFGray** [goolord/alpha-nvim#236]
files with `$` in them are failing to open, it tries to open a different file without the `$word` part in the file

eg a file listed as `app/routes/user.$name.tsx` ends up opening a new file named `user..tsx`

this makes me think the file name is being expanded by the shell, and the shell is looking for an [environment?] variable `$name` and then being expanded to an empty string

**Comment by goolord** [comment]
escape the "$" with "\". so "app/routes/user.\$name.tsx ". also, please do not use this issue tracker for tech support

**Comment by DanielFGray** [comment]
How do I, as a user of alpha, escape the `$` in a file name listed in the MRU list?

**Comment by goolord** [comment]
oh, I apologize, I misread the issue initially. I get a lot of people opening issues to ask questions unrelated to the plugin, I didn't mean to be dismissive. this is indeed something that should be fixed by the plugin

**Comment by goolord** [comment]
it's not the shell, it must be some overloading the `:e` command does. should be an easy fix

**Comment by goolord** [comment]
fixed in https://github.com/goolord/alpha-nvim/commit/331d55eb18d6e42bda4a183863a681be3ee11370
