### ISSUE TITLE
Alpha screen no longer shown at startup on nvim head

### ISSUE THREAD

**Issue by technicalpickles** [goolord/alpha-nvim#238]
I updated to neovim HEAD this morning (https://github.com/neovim/neovim/commit/bec13cfcafe73d33ed707b690fd924b1f52241f8), and realized that I no longer see the Alpha screen at startup.

On closer look, it seems like the default neovim screen is shown briefly and then an empty file is opened:

https://github.com/goolord/alpha-nvim/assets/159/19126f50-f931-4d03-bf84-6177334ed173

I realize the follies of HEAD, but figure on sharing in case it means something needs to be fixed in alpha or neovim.

**Comment by mrs4ndman** [comment]
Can replicate and confirm, having the same behaviour :)

**Comment by technicalpickles** [comment]
I forgot to mention, I can call the command `Alpha` directly. If I am reading this source correctly... https://github.com/goolord/alpha-nvim/blob/63a860e7ed3ae41ee92481ea65a48fb35431ae21/lua/alpha.lua#L756-L766

It's the `VimEnter` that ultimately triggers it on load. Maybe some of the behavior around `nvim_create_autocmd` or `nvim_create_augroup` changed?

**Comment by jdrouhard** [comment]
Bisected to neovim/neovim@b051b131f5ce99ffe1b1bc22a2032ebc886e4e35. No clue why that's the commit that broke this--could be another unforeseen side effect from the recent refactorings of buffer and window code in upstream neovim.

**Comment by TwIStOy** [comment]
After [b051b13](https://github.com/neovim/neovim/commit/bec13cfcafe73d33ed707b690fd924b1f52241f8), the behavior of `line2byte` has changed [neovim#24915](https://github.com/neovim/neovim/issues/24951). Maybe `alpha-nvim` should change how to detect [if should ship](https://github.com/goolord/alpha-nvim/blob/main/lua/alpha.lua#L576)?

**Comment by Jay-Madden** [comment]
it looks like this is broken for me again on latest neo head commit
```
➜ vim --version
NVIM v0.10.0-dev-2049+gfbe40caa7-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info```
