### ISSUE TITLE
Always skipped when remembering the last open buffers

### ISSUE THREAD

**Issue by naquad** [goolord/alpha-nvim#242]
Since 26d95031e2c624c5317dbdce386eb89f9356d4c0 Alpha is never shown with the `'shada` (aka `'viminfo`) += `%` which recovers the buffer list.

**Comment by goolord** [comment]
can you elaborate? I don't think I understand what `'shada` is

**Comment by naquad** [comment]
Pardon my terseness.

`'shada` is an [option](https://neovim.io/doc/user/options.html#'shada'), before ShaDA implementation in NeoVIM it was known as `'viminfo` (actually ShaDA supersedes the `'viminfo` but no matter).

It allows you to save various info about the NeoVIM sessions. One of the options (`%`) allows to remember the open buffer list.

**Comment by goolord** [comment]
oh I see, I had to close nvim with a listed buffer first. ok, I'll see if I can fix this

**Comment by goolord** [comment]
should be fixed in https://github.com/goolord/alpha-nvim/commit/234822140b265ec4ba3203e3e0be0e0bb826dff5 @naquad can you test?

**Comment by naquad** [comment]
Works for me! Thank you for the fix :)
