### ISSUE TITLE
 The shortcut keys do not update when the root directory is modified.

### ISSUE THREAD

**Issue by ck961018** [goolord/alpha-nvim#251]
I have configured a plugin for navigating to the root directory. When the root directory is changed, alpha will redraw the buffer, but the shortcut keys do not get updated.

The source code appears that only the start function updates the shortcut keys, whereas the root directory modification calls the redraw function.

I really appreciate this plugin, and if possible, I hope the issue can be resolved.

**Comment by goolord** [comment]
should be hotfixed in https://github.com/goolord/alpha-nvim/commit/29074eeb869a6cbac9ce1fbbd04f5f5940311b32

at some point i want to handle keymaps in a more robust way
