### ISSUE TITLE
Unlisted dependency on plenary

### ISSUE THREAD

**Issue by NickHackford** [goolord/alpha-nvim#259]
Installing this on NixOS and attempting to use the theta theme blows up the neovim config with unhelpful error messages until I also installed telescope. This dependency should be mentioned in these docs.

**Comment by goolord** [comment]
ah yeah I didn't originally author that file so i totally glazed over its dependency on plenary. i'll see about removing it or at least documenting it

**Comment by goolord** [comment]
theta's dependency on plenary is listed in the readme now https://github.com/goolord/alpha-nvim/commit/1356b9ef31b985d541d94314f2cf73c61124bf1d
