### ISSUE TITLE
Error 5108: Invalid buffer id: 1

### ISSUE THREAD

**Issue by zeitchef** [goolord/alpha-nvim#26]
I can't quite figure out why this is happening, but I'm getting the above error occasionally (see screenshot):

<img width="1440" alt="Screen Shot 2021-09-16 at 14 22 24" src="https://user-images.githubusercontent.com/6670659/133611878-8abd7d08-e2d9-47cb-92a8-0a86dc4e2465.png">

**Comment by goolord** [comment]
hmm, maybe on fast machines this code can get called before the buffer is even created. i can `pcall` deleting the buffer but then sometimes you would just have a hanging empty buffer. better than erroring, i guess

**Comment by goolord** [comment]
pushed a hotfix in https://github.com/goolord/alpha-nvim/commit/9df1a905018dfc788f0938dccdecf34c97bc9e9b, feel free to reepoen if you encounter it again
