### ISSUE TITLE
neo-tree on left alpha on right

### ISSUE THREAD

**Issue by iomari** [goolord/alpha-nvim#261]
Greetings,
How can I get neo-tree on the left and alpha on the right on startup like the attached screenshot?
I'm using lazy.

"https://imgur.com/YHf3qnG"

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/blob/1356b9ef31b985d541d94314f2cf73c61124bf1d/doc/alpha.txt#L286

this should help you get started
