### ISSUE TITLE
Alpha adjusts itself when opens looks weird

### ISSUE THREAD

**Issue by niksingh710** [goolord/alpha-nvim#264]
```lua
{
  "goolord/alpha-nvim",
  lazy = false,
  config = function()
    require("alpha").setup(require("alpha.themes.dashboard").config)
  end,
}
```

my config in lazy nvim

![output](https://github.com/goolord/alpha-nvim/assets/60490474/2c370706-f966-495d-93fb-ede17e674670)

**Comment by goolord** [comment]
can you post the output of `nvim --version` and also perhaps link your neovim configuration? does this happen with the debug configuration? https://github.com/goolord/alpha-nvim/blob/main/debug/DEBUG.md

**Comment by niksingh710** [comment]
nvim version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
for reference, my config is at [config](https://github.com/niksingh710/nvim)

in my testing I found out that it not from `alpha`, it is because of `statuscol` plugins that I have for `nvim-ufo`
