### ISSUE TITLE
Auto-Opening Alpha and Neotree

### ISSUE THREAD

**Issue by EvanZhouDev** [goolord/alpha-nvim#270]
I'm trying to have it so that when I start Neovim, Neotree is opened to the left, with Alpha opened to the right.

This is what I have so far in my Lua config:
```lua
if vim.fn.argc() == 0 then
  require'alpha'.setup(require'alpha.themes.dashboard'.config)
  vim.cmd("autocmd User AlphaReady Neotree")
else
  vim.cmd("autocmd VimEnter * Neotree")
end
```

However, when I do this, Alpha, which opens on the right, doesn't have its contents centered (Similar to #110). I understand (and have checked) that the fix in #110 works if I run `:Neotree` manually, but for some reason, doing an `autocmd` doesn't.

I'm quite new to Neovim, so if anyone can help me fix the Lua script to do this, it will be greatly appreciated!

**Comment by goolord** [comment]
there is an autocmd event that fires when `Alpha` opens https://github.com/goolord/alpha-nvim/blob/41283fb402713fc8b327e60907f74e46166f4cfd/doc/alpha.txt#L286

**Comment by EvanZhouDev** [comment]
@goolord I have already used this command in my code, and it still doesn't correctly align the `Alpha` window. I also figured out how to solve my second issue by checking `argc`...

```lua
if vim.fn.argc() == 0 then
    require("alpha").setup(require("alpha.themes.theta").config)
    vim.cmd("autocmd User AlphaReady Neotree")
else
    vim.cmd("autocmd VimEnter * Neotree")
end

```

**Comment by EvanZhouDev** [comment]
@goolord I was able to figure it out! Using `vim.schedule` helps it execute after Alpha finishes setting up, and Alpha detects the window resize this way.

```lua
if vim.fn.argc() == 0 then
    require("alpha").setup(require("alpha.themes.theta").config)
    local function start_up_func()
        vim.cmd("Neotree reveal")
    end
    vim.schedule(start_up_func)
else
    vim.cmd("autocmd VimEnter * Neotree")
end

```
