### ISSUE TITLE
About redraw part of the content

### ISSUE THREAD

**Issue by jinzhongjia** [goolord/alpha-nvim#284]
## How to redraw part of the content? 
I have a ~/code path that stores projects I often develop, but there may be too many folders in it, which will make it impossible to display them all on alpha (the height of the buffer will exceed the height of the split window), so I want to implement a page turning function
![image](https://github.com/goolord/alpha-nvim/assets/41784264/d6028d6f-80cf-4f45-bde6-b70f9db74e90)

**Comment by goolord** [comment]
example:
https://github.com/goolord/alpha-nvim/blob/41283fb402713fc8b327e60907f74e46166f4cfd/lua/alpha/themes/startify.lua#L232-L242

atm there's no way to redraw just one section, you just call `alpha.redraw` whenever you want to redraw any part of the screen. for your purpose calling `vim.cmd('AlphaRemap')` would also be necessary

**Comment by jinzhongjia** [comment]
Can I modify the config directly through `setup`?

**Comment by goolord** [comment]
yes, if there is any existing setup function you should call it in the body of the new function like so
```lua
setup = function ()
  config.setup()
  launchNukes()
end
```
