### ISSUE TITLE
How to show ANSI escaped colors ASCII art?

### ISSUE THREAD

**Issue by hirenchauhan2** [goolord/alpha-nvim#292]
Hi,

I'm looking for a way to show the ASCII art  with colors which I generated using [RASCII](https://github.com/orhnk/RASCII) tool. But I'm unable to render the output correctly on the dashboard in neovim. I've seen in the wiki people do mapping the each segments with some text and highlight that block. How to do with with ANSI escaped colors text?

Here's the Zenitsu ASCII art I want to display on the dashboard.

![image](https://github.com/user-attachments/assets/7d6b2c44-1427-47d4-88cd-49b239743675)

**Comment by goolord** [comment]
i think someone somewhere has written code that generates code for the vim highlighted version of ansi escaped colors for alpha, but you could also just the terminal element

**Comment by hirenchauhan2** [comment]
Got it, thanks!
