### ISSUE TITLE
Highlighting MRU Shortcuts

### ISSUE THREAD

**Issue by adamgulyas** [goolord/alpha-nvim#295]
After lots of experimentation, I can't seem to find a way to customize highlights on the `mru` and `mru_cwd` shortcuts in startify. I'm able to set the highlight of the section titles, but the list of mru shortcuts are generated by a call to the mru library with:

```
val = function()
  return { mru(10) }
end
```

When I inspect the MRU `val` property I see this table:

```
startify.section.mru.val = { 
  {
    type = "padding",
    val = 1
  }, {
    opts = {
      hl = "SpecialComment"
    },
    type = "text",
    val = "MRU"
  }, {
    type = "padding",
    val = 1
  }, {
    type = "group",
    val = <function 1>
  } 
}
```
  
My guess is that the last element's `val = <function 1>` is the call to `mru()` which generates the shortcuts. Since this is a function and not a list of elements, I'm wondering if there is a way to customize highlights for the generated MRU  **[ key ]** shorcuts in startify:

<img width="90" alt="image" src="https://github.com/user-attachments/assets/c889ecbb-6fd6-41fc-8f7b-ee9b16017943">

Can anyone confirm whether this is possible? 🙏

**Comment by goolord** [comment]
if you want to get that granular in customizing alpha i suggest just copying and modifying the entire startify file
