### ISSUE TITLE
Error on startup: attempt to call global 'from_nil'

### ISSUE THREAD

**Issue by JanValiska** [goolord/alpha-nvim#3]
Hi, 

I tried install your nice plugin but right after startup I got:

```E5108: Error executing lua ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:82: attempt to call global 'from_nil' (a nil value)```

Installed using packer:
``` 
use {
        'goolord/alpha-nvim',
        requires = {'kyazdani42/nvim-web-devicons'},
        config = function()
            require'alpha'.setup(require'alpha.themes.startify'.opts)
        end
}
```

Thanks for fixing :)

**Comment by goolord** [comment]
ah sorry, pushed a commit that should fix this.

**Comment by JanValiska** [comment]
Works perfectly. Thanks again for this plugin. Awesome.
