### ISSUE TITLE
Bug: String cannot  contain newlines

### ISSUE THREAD

**Issue by guilhermeprokisch** [goolord/alpha-nvim#31]
I'm getting this error using startfy

![image](https://user-images.githubusercontent.com/12011070/134258461-3088e2bd-d79c-489e-a269-51a0fbdf3d14.png)

**Comment by goolord** [comment]
what does your alpha config look like? this is expected behavior i think

**Comment by goolord** [comment]
closing, feel free to reopen if you have more details
