### ISSUE TITLE
bug: lua functions in dashboard button automatically executed

### ISSUE THREAD

**Issue by onexbash** [goolord/alpha-nvim#310]
I noticed a weird bug, that causes lua functions that are passed to the dashboard.button() function are executed without pressing the trigger key.

For example:
`dashboard.button("y", "🔭 explorer", print("test"))`
instantly prints "test" when alpha is opened.

Whats weird is that this doesnt happen for:
`dashboard.button("f", "🔭 fuzzyfind", require("telescope.builtin").find_files)`

Here's an overview of my complete alpha config:
![CleanShot 2024-10-30 at 17 33 38](https://github.com/user-attachments/assets/87057e63-1c36-46d6-8256-c19bad23e6e4)

**Comment by goolord** [comment]
that is expected behavior, what you should write is
`dashboard.button("y", "🔭 explorer", function () print("test") end)`

**Comment by koopa1338** [comment]
I have the same issue but not with a lua function but with Mason as a command:
```lua
local M = {
  "goolord/alpha-nvim",
  dependencies = { "kyazdani42/nvim-web-devicons" },
  event = "VimEnter",
}

M.config = function()
  local alpha = L "alpha"
  local dashboard = L "alpha.themes.dashboard"

  -- Set menu
  dashboard.section.buttons.val = {
    dashboard.button("e", "  New file", "<cmd>enew<CR>"),
    dashboard.button("1", "󰚰  Plugins", "<cmd>Lazy<CR>"),
    dashboard.button("2", "󰚰  Update Treesitter", "<cmd>TSUpdate<CR>"),
    dashboard.button("3", "󱃲  Mason", "<cmd>Mason<CR>"),
    dashboard.button("4", "✙  Check", "<cmd>checkhealth<CR>"),
    dashboard.button("q", "󰅚  Quit NVIM", "<cmd>qa<CR>"),
  }

  alpha.setup(dashboard.opts)
end

return M
```
This opens Mason on `VimEnter`
