### ISSUE TITLE
Option to ignore file types

### ISSUE THREAD

**Issue by TxHawks** [goolord/alpha-nvim#35]
Is there an option to ignore certain file or file types? Something akin to Startify's `skiplist`

Couldn't find anything in the docs

**Comment by goolord** [comment]
nope, I will write something up when I get the chance

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/commit/07de411522337b8881413011ba74e3071d0bb48a

example in docs

**Comment by TxHawks** [comment]
Thanks!
