### ISSUE TITLE
highlight group for fortunes doesn't work

### ISSUE THREAD

**Issue by abzcoding** [goolord/alpha-nvim#40]
first off, tyvm for your work on this 👍 

i'm setting `hl="Comment"` for my footer, but sadly it doesn't work

here is the code that i'm using
```lua
local fortune = require "alpha.fortune"()
local footer = {
    type = "text",
    val = fortune,
    opts = {
      position = "center",
      hl = "Comment",
      hl_shortcut = "Comment",
    },
  }
```
and this is what i get
<img width="831" alt="Screen Shot 2021-10-18 at 5 29 32 PM" src="https://user-images.githubusercontent.com/10992695/137746462-5d8460ef-d998-4768-b063-d9252ab19ca3.png">

also when i add this part
```lua
local fortune = require "alpha.fortune"()
fortune = fortune:gsub("^%s+", ""):gsub("%s+$", "")
```
i get sth like this
<img width="647" alt="Screen Shot 2021-10-18 at 5 32 12 PM" src="https://user-images.githubusercontent.com/10992695/137746635-e2107fb7-f067-4bad-823f-b105abd37cf7.png">

do you have any idea why it doesn't work?
here is my config in case you need it
https://github.com/abzcoding/lvim/blob/main/lua/user/dashboard.lua#L50

**Comment by goolord** [comment]
i did not inspect the fortune pr thoroughly enough ' _ '

basically the problem is that fortune was returning a string with newlines in it, which is prone to all sorts of nasty bugs so i decided newlines will be delimited by indices in a table
