### ISSUE TITLE
How to remove statusline

### ISSUE THREAD

**Issue by Leiyi548** [goolord/alpha-nvim#42]
I wanted to remove statusline, but I didn't see how to do it
![image](https://user-images.githubusercontent.com/76139422/139609915-2cee14ee-597e-4f8b-a904-f689f27826d6.png)

**Comment by goolord** [comment]
same as hiding the tabline but just replace with however you would load / unload your statusline
`    autocmd FileType alpha set laststatus=0 | autocmd BufUnload <buffer> set laststatus=whatever`
there isn't really a better/more general way to do this and having filetype specific statuslines generally sucks if you're not already using a statusline plugin, in which case it's that plugin's responsibility

**Comment by Leiyi548** [comment]
@goolord  Thankyou!
