### ISSUE TITLE
[Help ] How to disable another plugin when in dashboard

### ISSUE THREAD

**Issue by dinhmai74** [goolord/alpha-nvim#43]
I am using[indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim). And disable it when in the dashboard like this.

`require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    context_patterns = {
        "def", "class", "return", "function", "method", "^if", "^while",
        "jsx_element", "^for"
        -- ... and you can add more
    },
    buftype_exclude = {"terminal"},
    filetype_exclude = {"dashboard"}
}
`
Did I do anything wrong? 
![image](https://user-images.githubusercontent.com/40544043/139838059-8e715c00-638c-4f85-81d6-8780dc06ea16.png)

**Comment by l-kershaw** [comment]
The filetype of an alpha buffer is `alpha` not `dashboard`. So changing your `filetype_exclude` to `{"alpha"}` should work.

**Comment by dinhmai74** [comment]
Cool, it works. Thank a lot @l-kershaw
