### ISSUE TITLE
Rendered incorrectly with trigger key åäö

### ISSUE THREAD

**Issue by sQVe** [goolord/alpha-nvim#53]
👋🏼 

I'm noting that the button is rendered slightly off when using a key like `ö`. I'm using this:
```lua
dashboard.button('ö', '📝  Find file', ':lua require("plugins.navigation.telescope").find_files()<CR>'),
```
which renders to:
![image](https://user-images.githubusercontent.com/2284724/142701292-8e076477-d61d-44b2-a121-51fd3c40b760.png)

**Comment by goolord** [comment]
should be fixed in https://github.com/goolord/alpha-nvim/commit/e48f551a943b37bccbb974d537a958abdb97d1af
lmk if it persists for you :black_heart:
