### ISSUE TITLE
Don't add spaces to center on lines with empty content

### ISSUE THREAD

**Issue by augustocdias** [goolord/alpha-nvim#57]
In my setup I like to highlight trailing spaces in lines so I can easily remove them when I accidentally add, and this cause alpha to behave like the image bellow when there are lines with empty content (the light yellow ones).

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1080789/143218762-578220b4-dc49-4627-be4b-fbc4814bede3.png">

I was wondering if its possible for the plugin to check if the current line being printed is empty and if so just break the line instead of adding the spaces to center it.

**Comment by goolord** [comment]
are you using `list`? you can add `set nolist` to a filetype command or in `opts.setup`

it's possible to do as your suggesting but i would prefer not to for various reasons

**Comment by goolord** [comment]
actually, `nolist` is already set, so i'm not sure how you're even rendering those highlights. whatever plugin/code you're using, you just disable it when ft=alpha

**Comment by augustocdias** [comment]
It is not a plug-in. It is simply calling highlight on what matches a regex

```
vim.cmd('highlight ExtraWhitespace ctermbg=darkcyan guibg=darkcyan')
vim.cmd('match ExtraWhitespace /\\s\\+$\\|\\t/')

```

**Comment by goolord** [comment]
yeah, then i would suggest setting up `opts.setup` or a filetype autocmd to call `highlight ExtraWhitespace NONE` for alpha

**Comment by goolord** [comment]
hopefully i'm not coming across as rude, i just don't want to support edge cases for what are ultimately user configuration problems. it's a sisyphean task, tbh. it's just a side effect of trying to jerry-rig a gui out of a program that was only really ever designed to edit text files

**Comment by augustocdias** [comment]
I understand. No worries.

**Comment by augustocdias** [comment]
@erichaus no. I don't think it was/is useful to my workflow and I just dropped it altogether. I usually open nvim directly into the folder I'm going to work. The shortcuts were not really useful to me.
