### ISSUE TITLE
How can I go to a path from the menu?

### ISSUE THREAD

**Issue by marcelarie** [goolord/alpha-nvim#59]
IDK if its a collision with other plugin key-binds but I can't open any file.
Its there any documentation part that I am missing?

my config:
```lua
local startify = require("alpha.themes.startify")
require("alpha").setup(startify.opts)
```

I use `NVIM v0.6.0-dev+644-ge4976cbd2`

**Comment by goolord** [comment]
yeah i don't know what's up with that, can you try using the minimal vimrc?
https://github.com/goolord/alpha-nvim/blob/main/debug/min-alpha-startify.lua

**Comment by goolord** [comment]
you may need to add some buttons to test keybindings, so you can copy this into min-alpha-startify to test

```lua
local startify = require("alpha.themes.startify")

startify.section.top_buttons.val = {
	startify.file_button("~/foo", "0"),
}

require("alpha").setup(startify.opts)
```

**Comment by goolord** [comment]
also, looking at your config illuminated something to me maybe, here in your config
https://github.com/marcelarie/nvim-lua/blob/main/lua/plugins/alpha/init.lua#L5-L8

you are typing `~/home/marcel`
which is going to expand to `/home/marcel/home/marcel`, which probably doesn't exist :)

**Comment by marcelarie** [comment]
Thanks! I copied that part from another config and I left the `~` 💀

But I think it must be from something else, before I did't have 
anything else than `local startify = require("alpha.themes.startify")
require("alpha").setup(startify.opts)` and it worked the same way. 

The normal behavior it's that you press the key inside the `[]` right?

For example in `[e] new file` will be `e`.

**Comment by goolord** [comment]
yes

**Comment by marcelarie** [comment]
Finally yes, this two where causing the problem:

```lua 
-- ; for :
vim.api.nvim_set_keymap("n", ";", ":", { noremap = true, silent = false })
vim.api.nvim_set_keymap("n", ":", ";", { noremap = true, silent = false })
```

**Comment by goolord** [comment]
ah, ok i think i can push a fix for this. i can use '<cmd>' where i use ':' in the keybindings

**Comment by goolord** [comment]
okay, fixed in https://github.com/goolord/alpha-nvim/commit/baae95f0dfb5d7084bdc558bf5e4f3be0d986390

this should be agnostic to `:` being remapped

technically this changes the behavior of all of the buttons in a few ways but i don't think it's that big of a deal; if anything the new behavior is probably preferable

i am legitimately surprised this keybinding hasn't caused you trouble with any other plugins though  ' 3 '

lmk if you're still having problems

**Comment by marcelarie** [comment]
Eveything works now, thank you!

Just fyi now this button does not work:
```lua
 startify.button("vi", "vim config", ":cd ~/.config/nvim/<CR>:e init.lua<CR>")
```

and this one works just fine:
```lua
 startify.button("vi", "vim config", "<cmd>cd ~/.config/nvim/<CR><cmd>e init.lua<CR>")
```
