### ISSUE TITLE
config help

### ISSUE THREAD

**Issue by barkanido** [goolord/alpha-nvim#60]
hey, a lua newbie here.
using the config example form the readme file:
```lua
use {
    'goolord/alpha-nvim',
    requires = { 'kyazdani42/nvim-web-devicons' },
    config = function ()
        require'alpha'.setup(require'alpha.themes.startify'.opts)
    end
}
```
gives me:
```
E5113: Error while calling lua chunk: .config/nvim/lua/init.lua:122: attempt to call global 'use' (a nil value)
```

**Comment by goolord** [comment]
the example in the readme assumes you're using the https://github.com/wbthomason/packer.nvim plugin manager to install plugins, if you've never installed a plugin before there will be more info there, it might be also fruitful to look at other people's configs 
(https://github.com/goolord/nvim)

**Comment by barkanido** [comment]
I am using vim-plug so in init.vim I have:
```vim
Plug 'goolord/alpha-nvim'
```
and in the sourced lua file I had this 'use'
what is the equivalent lua for this?

**Comment by goolord** [comment]
```vimL
Plug 'goolord/alpha-nvim'
Plug 'kyazdani42/nvim-web-devicons'

lua << EOF

require'alpha'.setup(require'alpha.themes.startify'.opts

EOF
```

this should work
