### ISSUE TITLE
[Question]  How to select multiple files?

### ISSUE THREAD

**Issue by amiroslaw** [goolord/alpha-nvim#67]
How to select multiple files like?  In the vim-startify I can select the file pressing `t` key.

**Comment by goolord** [comment]
not implemented yet, it's on my radar tho

**Comment by goolord** [comment]
k, a rudimentary version of this feature was added, bound to <M-CR> https://github.com/goolord/alpha-nvim/commit/5f3643cfd6a94f18cb1bc03ec86254c30c0c53be

**Comment by jmmendivil** [comment]
Any update on this? @goolord

**Comment by goolord** [comment]
yes, the feature has been a part of the plugin for 3 and a half years now. read the comment above yours
