### ISSUE TITLE
Please do not commit your doc/tags to remote repo

### ISSUE THREAD

**Issue by jdhao** [goolord/alpha-nvim#68]
The same issue [here](https://github.com/shaunsingh/nord.nvim/issues/52). Tags will be generated by plugin managers. There is no need to commit your tags file into remote repo, which will cause merging issues when git pull your remote reopo.

**Comment by goolord** [comment]
oopsies thanks for letting me know

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/commit/914efd31aa5c8ccfcbce745deb95981e7ebaeb96
