### ISSUE TITLE
How to centralize the startify theme

### ISSUE THREAD

**Issue by meijieru** [goolord/alpha-nvim#70]
How to achieve a similar effect with dashboard theme like centered startify?

**Comment by goolord** [comment]
changing `position = "center"` and adding a "width = x" to `opts` of each element might get you the effect you want without much trouble

**Comment by meijieru** [comment]
One problem I faced is the lengths within startify are not fixed.
So it's not trivial to use the `center` trick as dashboard.

**Comment by goolord** [comment]
the newer `theta` theme is like a centered startify theme

**Comment by meijieru** [comment]
Looks good, thx!
