### ISSUE TITLE
Startify theme: attempt to index a nil value

### ISSUE THREAD

**Issue by JanValiska** [goolord/alpha-nvim#8]
Hi,

when I configure alpha to use startify theme:

```
    use {
        'goolord/alpha-nvim',
        config = function()
            require'alpha'.setup(require'alpha.themes.startify'.opts)
        end
    }
```
I get error on startup:

```
packer.nvim: Error running config for alpha-nvim: ...ck/packer/start/alpha-nvim/lua/alpha/themes/startify.lua:64: attempt to index a nil value
```

Any idea how to solve?
Thanks

**Comment by JanValiska** [comment]
I printed oldfiles using `print(vim.inspect(oldfiles))` and what I can say is that in the history there is one non-text(binary) file that I accidentally opened yesterday. Maybe it is needed to handle binary files in the history separately. I suppose that there is missing icon for binary files.

**Comment by JanValiska** [comment]
So it looks like problem aren't binary files but files without extension. Since you are matching filename `fn:match("^.+(%..+)$"):sub(2)` and supposing that there is always match.

**Comment by JanValiska** [comment]
Something like this:
```
            local match = fn:match("^.+(%..+)$") 
            local ext = ''
            if match ~= nil then
                ext = match:sub(2)
            end
```
solves issue and uses default web-dev icon for files without extension.

**Comment by goolord** [comment]
hmm i fixed this already but it got clobbered somehow. i will push a fix for this

**Comment by goolord** [comment]
should be fixed in https://github.com/goolord/alpha-nvim/commit/2e6ef7cf5ed79e63e04bb625ef5dedb8c90de919
