### ISSUE TITLE
Header color and font size!

### ISSUE THREAD

**Issue by Sergey-Voskresenskiy** [goolord/alpha-nvim#86]
I looked through a lot of configs and could not figure out how to control the font size, color, family for the Header part of the dashboard alpha. I will be very grateful for any help and/or advice.
[My config](https://github.com/Sergey-Voskresenskiy/.dots/blob/master/nvim/lua/settings/alpha.lua)

**Comment by goolord** [comment]
vim runs in the terminal, are you expecting to be able to change the font size + family of *just* the header?

you can change the color though, https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L111

`opts = { hl = "MyHeaderHighlightGroup" }`

**Comment by Sergey-Voskresenskiy** [comment]
> vim runs in the terminal, are you expecting to be able to change the font size + family of _just_ the header?

Hope is the last to die. But thank you for your answer.

**Comment by goolord** [comment]
with https://github.com/goolord/alpha-nvim/pull/63 you might be able to approximate something like that by displaying an image or something, if your terminal supports that
