### ISSUE TITLE
Similar vim-startify features

### ISSUE THREAD

**Issue by Mte90** [goolord/alpha-nvim#9]
I want to migrate to this plugin so I can removed another viml dependence.
Right now of Startify I use various features https://github.com/mte90/dotfiles/blob/master/.vim/custom/custom-startify.vim

First of all I specify an ASCII custom text and center it.
I specify also the amount of files to see from recent files but also to show only Recent files and custom bookmarks.

Reading the documentation I didn't found anything about those settings.

Can you help me troubleshooting that?

**Comment by goolord** [comment]
there is an example of how to change the startify theme's header right here
https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L176

you are not the first person to claim to have read the docs and missed this, though. is there anything I can do to make it clearer?
startify.section.header is a text widget so `val` can be an array or a string as specified here https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L94

**Comment by Mte90** [comment]
It is not clear that variable is for the ASCII art seems something else.

Instead for the other one it is ffor bookmarks? like I can have a shortcut that open that folder/file?

**Comment by goolord** [comment]
also, please check the issue tracker. this has already been asked https://github.com/goolord/alpha-nvim/issues/4

i will add to the startify example to clarify how to add more buttons/shortcuts

**Comment by goolord** [comment]
https://github.com/goolord/alpha-nvim/commit/68c013dbcb74fe241737be7f70abf1f9a46068be added some docs for adding new buttons and made it more clear which option is the header. will update it with info on how to disable sections when i get the change

**Comment by goolord** [comment]
ok, it's documented a little better now
https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L178

**Comment by Mte90** [comment]
Now it is better thanks :-D
