### ISSUE TITLE
leader key assumption

### ISSUE THREAD

**Issue by icy-comet** [goolord/alpha-nvim#90]
https://github.com/goolord/alpha-nvim/blob/8ad63ffb2888a30019d082f08e0b63b9a96ee77c/lua/alpha/themes/dashboard.lua#L34

Unless I am mistaken, `SPC` refers to the Space(bar) key. And it's not clear in the documentation that behind-the-scenes `SPC` refers to whatever your leader key is.

We could either map it to the actual Space key or change the placeholder text from `SPC` to something else (maybe `Lead`).

I am aware that this only affects users using the default theme. But I am sure many would rather extend the default theme and just change the header and the buttons instead of maintaining a complete new theme.

**Comment by goolord** [comment]
made the string configurable in https://github.com/goolord/alpha-nvim/commit/78e48d7ec6b7005e0d3d5363ccfd9870d5a02b35

still mulling over what to change the default to
