### ISSUE TITLE
How to change colors of the header footer and buttons

### ISSUE THREAD

**Issue by tsjazil** [goolord/alpha-nvim#95]
I could n't figure out it checked the code but couldn't figure it out

**Comment by goolord** [comment]
pretty much every element type has https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L78 and buttons have https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L82

so changing the header for example would be `dashboard.section.header.opts.hl = "Red"`

**Comment by tsjazil** [comment]
could you give me an example of adding colors in that group    ` hl = "hl_group" | {{"hl_group", 0, -1}}`
